### ISSUE TITLE
Tutorial fails with format_A_X error

### ISSUE THREAD

**Issue by segasai** [ajwheeler/Korg.jl#135]
Hi, 

I wanted to give Korg a spin, and tried the tutorial, but I couldn't quickly make synthesize work 

* I have julia 1.6.1.
* I installed Korg using Pkg.add 

When doing this (following the tutorial)
```
julia> using Korg, PyPlot
julia> lines = read_linelist("/tmp/linelist.vald", format="vald")
... 

julia> atm = read_model_atmosphere("/tmp/s6000_g+1.0_m0.5_t05_st_z+0.00_a+0.00_c+0.00_n+0.00_o+0.00_r+0.00_s+0.00.mod")
Korg.ShellAtmosphere{Float64} with 53 layers

julia> synthesize(atm, lines, format_A_X(0), 4000, 4030);
ERROR: UndefVarError: format_A_X not defined
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1


```
I get format_A_X error. I see there were recently commits changing to format_A_X from to construct_abundances()
But construct_abundances(0) doesn't work either. 

Any suggestions what I am doing wrong ?  I'm guessing I may not be using the latest Korg version, TBH I don't know which version Pkg.add installs (but the docs only mention Pkg.add installation) 

Thanks

**Comment by ajwheeler** [comment]
That's embarrassing!  This is because, unfortunately, the past several versions of Korg only support Julia 1.7+.  So  `Pkg.add`, installed an old version with a different interface.  (You can run `?synthesize` in a REPL to see how to use the version you have.)  Everything should work correctly with Julia 1.7 or 1.8, and in now that the code is "out", I'm committed to keeping it working with older versions of Julia.

**Comment by segasai** [comment]
Ah I see. I was suspecting something like that. I think I saw when installing that I've got  Korg v0.7.6.after that  I also went to https://juliapackages.com/packages/korg and didn't see a version there, so got confused.
Thanks. I'll update julia and try again!

**Comment by segasai** [comment]
It works now with julia 1.8. Thanks!
