### ISSUE TITLE
Fitting for resolving power

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#259]
It should be possible to fit for resolving power with `fit_spectrum`.  This is not computationally difficult, just a matter of working out the interface nicely, since it precludes using a precalculated LSF matrix.

**Comment by ajwheeler** [comment]
Related to this, it should be possible to provide a prior for each paramter, or perhaps a joint prior.  I've worried that $R$ will turn out to be quite degenerate with $v_\mathrm{mic}$ and $v \sin(i)$.

**Comment by andrew-saydjari** [comment]
Are we imagining that this is necessary because R fit to skylines/FPI lines is not good enough due to variable seeing?

**Comment by ajwheeler** [comment]
I'm not sure what's the biggest contributor to badly-estimated $R$, but a couple people (not working on SDSS spectra) have asked me if it's possible to do.

**Comment by sp-shah** [comment]
I mainly asked for convenience. I think $R$ also changes through the spectrum. For instance, the red and blue spectra (that are usually stitched and analyzed together) of MIKE differ in resolving powers. Although that just means you should have two different $R$s. Additionally, the line widths are different between lines, due to unknown atomic data, blends, noise in that certain region etc. It's easier to sweep all of these factors into the smoothing fit of the line [small wavelength windows rather than the full spectrum] and obtain a good-looking fit, especially for the weak lines and/or blended lines. But it's very much possible that the difference won't be massive. I haven't tested too much.

**Comment by sp-shah** [comment]
Could providing an initial estimate of $R$ for fitting vmicro and other stellar parameters, but keeping $R$ a free parameter for abundance fits of wavelength regions (while keeping vmicro and vsini constant) work?

**Comment by ajwheeler** [comment]
> Could providing an initial estimate of for fitting vmicro and other stellar parameters, but keeping a free parameter for abundance fits of wavelength regions (while keeping vmicro and vsini constant) work?

I think this is a very reasonable approach in cases where you can't estimate the resolving power better.

If you have an estimate of $R(\lambda)$, it's worth nothing that you can use that directly in Korg.

Also, thinking about this some more, I think what I will actually do is make it possible to fit for $v_\mathrm{mac}$.  This is a "traditional fudge factor" to account for large-scale turbulent velocities that is exactly equivalent to a constant $R$.  (So in some sense, this is primarily about what the function names and units.)

**Comment by ajwheeler** [comment]
I'm closing this issue because I've become convinced that #353 is the right way forward.
