### ISSUE TITLE
documentation for generating grids on a SLURM cluster

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#303]
@yingyisong

**Comment by andrew-saydjari** [comment]
A clean APOGEE version of this is integrated as part of apMADGICS.jl here: https://github.com/andrew-saydjari/apMADGICS.jl/blob/main/src/prior_build/sample_Korg.jl

I have also attached a fairly clean example script for DESI that I wrote for and have used with a student. Uploaded as a zip file because .jl is not accepted... 👎🏽 

 [gen_grid_desi.jl.zip](https://github.com/user-attachments/files/15811619/gen_grid_desi.jl.zip)

**Comment by ajwheeler** [comment]
I'm assuming you don't mind if I add a modified version of this to the documentation?  I'll let you review the PR, obviously.

**Comment by andrew-saydjari** [comment]
I do not mind at all, this was just an example script to get you started.
