### ISSUE TITLE
spherical transfer microöptimizations

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#76]
```
    for (μ_ind, μ_surface) in enumerate(μ_surface_grid)
        # impact parameter of ray
        b = R * sqrt(1 - μ_surface^2)
```

Not necessarily worth doing in this PR, but I don't think that you need to take a sqrt here (which is moderately expensive). 

Instead, I think you could directly compute b2 here and just use that throughout the rest of this loop. To do that, you would also have to precompute the squared radii before the for-loop, (that would also save you some work on line 73).

_Originally posted by @mabruzzo in https://github.com/ajwheeler/Korg.jl/pull/74#discussion_r728401520_

```
        #calculate the index of the lowest layer the ray passes through
        i = argmin(abs.(radii .- b))
        if radii[i] < b
            i -= 1
        end
```

Another potential optimization: if `radii` is sorted, I think you could replace this section with  `searchsortedfirst`.

_Originally posted by @mabruzzo in https://github.com/ajwheeler/Korg.jl/pull/74#discussion_r728403172_

**Comment by mabruzzo** [comment]
I don't know what possessed me to look at this, but here are some additional micro-optimizations to be made: (I would prioritize number 2, below before considering any of the other options on this page). I think it has the potential to deliver the most significant performance improvements...

---


1. The call to `reverse` is allocating a new array. You should use a `view` instead. In other words, replace
```julia
            τ_prime = τ[end:end, :] .+ [cumsum(reverse(dτ[2:end, :], dims=1), dims=1) 
                                        ; zeros(size(τ[end:end, :]))]
```
with 
```julia
            τ_prime = τ[end:end, :] .+ [cumsum(view(dτ, size(dτ, 1):-1:2,:), dims=1), dims=1) 
                                        ; zeros(size(τ[end:end, :]))]
```
---

2. My strongest suggestions is to consider refactoring the loop to have explicitly handle wavelengths one at a time. The result would be a formulation similar to the following (I have not applied any of my other recommendations here):
```julia
    for (μ_ind, μ_surface) in enumerate(μ_surface_grid)
        # impact parameter of ray
        b = R * sqrt(1 - μ_surface^2)
        
        #calculate the index of the lowest layer the ray passes through
        i = argmin(abs.(radii .- b))
        if radii[i] < b
            i -= 1
        end
        if i == 1 || i == 0
            I[:, μ_ind] .= 0
            continue
        end #can eliminate for i == 1?

        #ds is the path length through each layer
        ds = -diff(@. sqrt([R ; radii[1:i]]^2 - b^2)) 
        for λ_ind in 1:size
            
            dτ = α[1:i, λ_ind] .* ds
            τ = cumsum(dτ)

            I[j, μ_ind] = transfer_integral(τ, S[1:i, λ_ind]; plane_parallel=false)

            # the compiler might realize that you could pull this if-statement 
            # out of the inner for-loop
            if b > r0 
                #if the ray never leaves the model atmosphere, include 
                #the contribution from the other side of the star
                τ_prime = τ[end] .+ [cumsum(reverse(dτ[2:end])); 0.0]
                I[λ_ind, μ_ind] += transfer_integral(τ_prime, S[1:i, λ_ind]; plane_parallel=false)
            else #otherwise assume I=S at atmosphere lower boundary
                I[λ_ind, μ_ind] += exp(-τ[end]) * S[end]
            end
        end
    end
```
3. I would also consider pre-allocating the buffers that hold `dτ`, `τ` and revising the `τ_prime = τ[end] .+ [cumsum(reverse(dτ[2:end])); 0.0]` line to avoid allocating a new array every time that it's called (you could pre-allocate a buffer or if you're feeling ambitious, you could just overwrite the values in `τ`).

The benefit to doing all of this, is that all the data needed for the entire inner loop can fit into the L1 data cache (at least under most conditions). To illustrate this, imagine that you have ~100 atmospheric layers. Thus, in the inner-most loop we consider ~6 arrays containing 100 value : `ds`, `dτ`, `τ`, `τ_prime`, `S[1:i, λ_ind]`, and `α[1:i, λ_ind]`. Altogether, that's about 30% of a 16 kilobyte L1 data cache.

Now, I've been wrong before about what the julia can and cannot do, but I would be fairly stunned if the compiler transformed the existing code to this control flow. It's probably worth giving this a try.

---

Along the lines of the prior optimization, it might be beneficial to precompute `b`, `i`, and `ds` before the loops and swap the order of loops so that you iterate over wavelength at the top level, and `μ_ind` on the inner level. The hypothetical benefit is that each time you enter the inner loop, the computer only needs to load `b`, `i`, and `ds[:,μ_ind]` (which could be stored together at one location in memory) into the L1 cache instead of `S[1:i, λ_ind]` and `α[1:i, λ_ind]` (which are stored in separate locations). I'm less sure that this optimization would pay off.

---

Lastly, I just thought that I would point out that the **only** algorithmic barrier to SIMD vectorization of `transfer_integral` is the fact that `exp` is not vectorized. Unlike the line profiles, there really isn't any other branching to consider.

**Comment by ajwheeler** [comment]
#97 closes this, except for the inefficiencies with tau_prime, which I've mentioned in a comment.
